### ISSUE TITLE
Fail to reproduce OICR results, while make it with PCL

### ISSUE THREAD

**Issue by youthHan** [bradezard131/wsod#5]
Hi, 
Thank you for the reimplementation of the WSOD methods.

With the hint in previous issues and the PCL config file provided, I can reproduce the result of PCL as 43.8, comparable to your claimed mAP 44.21.
However, I fail to reproduce the claimed mAP 40.8 with the config file provided. (My result is 36.9 for oicr_vgg.yaml; 37.3 for oicr_vgg_dilated.yaml and I have changed the `MAX_ITER` to 70000.)

Could you please help me with this?

**Comment by liz6688** [comment]
Hi,
It seems that you running the code smoothly. Can you tell me how the proposal is generated? I got the error FileNotFoundError: No such file or directory: 'anno/proposals_trainval.pkl'. 
Thanks.

**Comment by bradezard131** [comment]
I can't reproduce the issue. I've also abandoned using this for my experiments since I got fed up with the detectron2 docs being terribly incomplete and the FAIR team's approach of "It's a library so use it how you want" rather than documenting the expected IO for many components.

@liz6688 You need the proposals in detectron2 format, which IIRC is a dict of some sort. I'm not sure I have them anymore. Look at their precomputed proposals and match the format using the boxes from the standard selective-search .mat file, which should be in the original Fast RCNN repository

**Comment by youthHan** [comment]
@bradezard131 Thank you for the response. I'll try it on a different server and I hope the proposal file is correct, as the PCL can reproduce the results.
I used mmdetection (1.x versions) in my research and it has the same issue with the terribly incomplete docs. In their newly release v2.0, a more complete documentation has been claimed. Maybe you can have a look there.

@liz6688 The selective-search proposals in .pkl file could be found in [PCL.pytorch](https://github.com/ppengtang/pcl.pytorch). As figured out by Ezard, you need to transfer it to detectron2 format indicated [here](https://github.com/facebookresearch/detectron2/blob/048610e34adb7fc8dbbbb46dc05e0e75cdb028e2/detectron2/data/build.py#L106) or [here](https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts), maybe depending on the detetron2 version.

**Comment by liz6688** [comment]
@bradezard131 @liz6688 Thank you for the response. I'll try it soon.
